name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: Protocol Breaking Changes 🚨
    labels:
      - breaking-protocol
  - title: Local Breaking Changes ⚠️
    labels:
      - breaking-local
  - title: Other Changes
    labels:
      - "*"

change-template: '- $TITLE (#$NUMBER by @$AUTHOR)'
template: |
  <A manual one-liner with changes>.

  ## ✨ Highlights: 

  <A manual one-liner with changes>.

  ## 🔗 Links

  ### 🐳 Images: 

  On [DockerHub](https://hub.docker.com/r/blockstack/sbtc/tags?name=$NEXT_PATCH_VERSION):

  - [`blockstack/sbtc:signer-$NEXT_PATCH_VERSION@sha256:<SignerDigest>`](https://hub.docker.com/layers/blockstack/sbtc/signer-$NEXT_PATCH_VERSION/images/sha256-<SignerDigest>)
  - [`blockstack/sbtc:blocklist-client-$NEXT_PATCH_VERSION@sha256:<BlocklistDigest>`](https://hub.docker.com/layers/blockstack/sbtc/blocklist-client-$NEXT_PATCH_VERSION/images/sha256-<BlocklistDigest>)

  ⚠️ Always use [immutable image tags](https://docs.docker.com/reference/cli/docker/image/pull/#pull-an-image-by-digest-immutable-identifier).

  🔎 Verify the attestation of these images using this [guide](https://docs.github.com/en/actions/security-for-github-actions/using-artifact-attestations/using-artifact-attestations-to-establish-provenance-for-builds#verifying-artifact-attestations-with-the-github-cli).

  ### 📙 Database migrations

  Here: [`signer/migrations`](https://github.com/stacks-network/sbtc/tree/$NEXT_PATCH_VERSION/signer/migrations).

  ## 🛠️ Upgrade Instructions:

  1. Stop your sBTC signer
  1. Backup your database
  1. Edit your configuration as instructed
  1. Apply database migrations (only if not running with the `--migrate-db` flag)
  1. Update your sBTC images as specified above
  1. Restart your sBTC signer and blocklist client

  ## What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/stacks-network/sbtc/compare/$PREVIOUS_TAG...$NEXT_PATCH_VERSION
