[package]
name = "emily-openapi-spec"
version = "0.1.0"
edition = "2021"

[package.metadata.cargo-machete]
ignored = ["emily-handler", "utoipa", "serde_json"]

[build-dependencies]
emily-handler = { workspace = true, features = ["testing"] }
serde_json.workspace = true
utoipa.workspace = true
