# This file is used for running the dependencies of the sBTC signer.
#
# It is intended to become a template for the absolute minimum required
# dependencies to run the signer and used to adapt the devenv later. 
# See # TODO(536)

volumes:
  dynamodb_data:

networks:
  sbtc_signer:
    driver: bridge

services:

  signer:
    container_name: sbtc-signer
    build:
      context: .
      dockerfile: Dockerfile.signer
    volumes:
      - .:/data
    networks:
      - sbtc_signer
    working_dir: /data
    command: 
      - /bin/bash
      - -c 
      - . /root/.cargo/env && cargo run --target x86_64-unknown-linux-gnu --bin signer -- -c /data/signer/src/config/default.toml --migrate-db
    environment:
      RUST_BACKTRACE: 1
      RUST_LOG: info
      SIGNER_SIGNER__DB_ENDPOINT: postgres://devenv:devenv@sbtc-postgres/signer
    depends_on:
      postgres:
        condition: service_healthy
      bitcoind:
        condition: service_healthy