################################################################################
# Define test groups
################################################################################
[test-groups]
# Test group for integration tests that need to be run serially. Tests in this
# group will be run one at a time.
serial = { max-threads = 1 }

################################################################################
# Apply the 'serial' test-group to all integration tests which need to be run
# serially. This is primarily tests which need to interact with Emily as it is
# not run using `testcontainers` at the moment.
################################################################################

# All integration tests in the 'sbtc' package. This is because at the moment
# `testcontainers` are in the `signer` package, which can't be referenced by
# `sbtc`.
[[profile.default.overrides]]
filter = 'package(sbtc) & kind(test)'
test-group = 'serial'

# All integration tests in the 'emily-handler' package as these interact with
# Emily.
[[profile.default.overrides]]
filter = 'package(emily-handler) & kind(test)'
test-group = 'serial'

# Most integration tests in the 'signer' package can be run in parallel, but the
# few that do interact with Emily or for other reasons need to be run serially
# are individually listed here.
[[profile.default.overrides]]
filter = """
package(signer) & kind(test) & (
    test(/^zmq/) 
)
"""
test-group = 'serial'
threads-required = 100