[project]
name = "emily-cron"
version = "0.1.0"
description = "Cron job for updating deposit statuses in Emily"
requires-python = ">=3.13"
dependencies = [
    "requests==2.32.3",
    "btclib==2023.7.12",
]