## Log sources

# [sources.devenv_logs]
# type = "docker_logs"

## Prometheus Host metrics

[sources.host_metrics]
type = "host_metrics"
collectors = ["cpu", "disk", "load", "filesystem", "host", "memory", "network"]
scrape_interval_secs = 15

[sources.host_metrics.filesystem.mountpoints]
includes = ["/"]

[sources.host_metrics.disk.devices]
includes = ["/dev/root", "nvme*", "tmpfs"]

[sources.app]
type = "prometheus_scrape"
endpoints = [
    "http://host.docker.internal:9181",
    "http://host.docker.internal:9182",
    "http://host.docker.internal:9183",
    "http://sbtc-signer-1:9181",
    "http://sbtc-signer-2:9182",
    "http://sbtc-signer-3:9183",
]

## App Metric Sinks

[sinks.host_metrics_sink]
type = "prometheus_exporter"
inputs = ["host_metrics", "app"]
address = "0.0.0.0:9598"

## Log Sinks

# [sinks.loki_logs]
# type = "loki"
# inputs = ["devenv_logs"]
# endpoint = "http://loki:3100"

# [sinks.loki_logs.encoding]
# codec = "json"

# [sinks.loki_logs.labels]
# source = "vector"
