[package]
name = "idpack"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
thiserror.workspace = true

[dev-dependencies]
test-case.workspace = true
proptest.workspace = true
rand.workspace = true
assert_matches.workspace = true
