services:
  bitcoin:
    restart: on-failure
    build:
      context: bitcoin/
      dockerfile: Dockerfile.bitcoin
    ports:
      - "18443:18443"
      - "28332:28332"
    volumes:
      - ./bitcoin-regtest/bitcoin.conf:/root/.bitcoin/bitcoin.conf:ro
      - ./bitcoin-regtest/chainstate/testnet/:/chainstate
    entrypoint:
      - /bin/bash
      - -c
      - |
        set -e
        bitcoind
    environment:
      BITCOIN_DATA: /chainstate/bitcoin
  stacks-blockchain:
    # source: https://github.com/stacks-network/stacks-blockchain-docker/blob/66c54acef25e34cd08ccec44989d8bae5584270b/compose-files/common.yaml#L20C1-L42C8
    image: blockstack/stacks-blockchain:3.0.0.0.2
    restart: on-failure
    ports:
      - ${STACKS_CORE_RPC_PORT:-20443}:${STACKS_CORE_RPC_PORT:-20443}
      - ${STACKS_CORE_P2P_PORT:-20444}:${STACKS_CORE_P2P_PORT:-20444}
      - ${NODE_METRICS_PORT:-9153}:${NODE_METRICS_PORT:-9153}
    volumes:
      - ./stacks-testnet/Config.toml:/src/stacks-blockchain/Config.toml:ro
      - ./stacks-testnet/chainstate/:/root/stacks-blockchain/data
    command:
      [
        "/bin/stacks-node",
        "start",
        "--config",
        "/src/stacks-blockchain/Config.toml",
      ]
