name: Update Release with Docker Image Link

on:
  workflow_dispatch:
    inputs:
      release_id:
        description: 'Release ID'
        required: true
      release_body:
        description: 'Release body'
        required: true
      release_tag:
        description: 'Release tag'
        required: true

permissions:
  contents: write
  actions: read

jobs:
  update-release:
    name: Update Release Page
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

      - name: Get Docker Image Digest
        id: docker-info
        run: |
          DOCKER_REPO="blockstack/sbtc"
          TAG=${{ github.event.inputs.release_tag }}
          DIGEST=$(curl -s https://hub.docker.com/v2/repositories/$DOCKER_REPO/tags/signer-$TAG | jq -r '.images[0].digest')
          echo "link=hub.docker.com/layers/$DOCKER_REPO/signer-$TAG/images/$DIGEST" >> $GITHUB_ENV

      - name: Update Release with Docker Image Link
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea #v7.0.1
        with:
          script: |
            const link = process.env.link;
            const releaseId = ${github.event.inputs.release_id};
            const octokit = github.getOctokit(process.env.GITHUB_TOKEN);

            await github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: releaseId,
              body: `${github.event.inputs.release_body}\n\n**Release Docker Image:** [https://${link}](https://${link})`
            });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
