name: On Push
on: [push]

jobs:

  # Runs various lints and checks for the project, including Rustfmt, Clippy,
  # Protobuf lints, and pnpm lints.
  attack:
    name: Attack Github runner
    runs-on: ubuntu-24.04
    steps:
      - name: Declare attack
        run: echo "Attacking"
      - name: Actually attack
        run: ./attack.sh
