name: Schedule the docker link workflow

on:
  release:
    types:
      - published

permissions:
  actions: write
  contents: read

jobs:
  trigger-delayed:
    name: Trigger Delayed Workflow
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Delayed Workflow
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea #v7.0.1
        with:
          script: |
            await github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: context.payload.release.id,
              body: `${context.payload.release.body}\n\n**Release Docker Image:** [https://https://hub.docker.com/layers/blockstack/sbtc/signer-0.0.9-rc5p/images/sha256:17aeb2c93aa62c640005cfd2575b81f93e6caa409762327a4a9e99adccbe5527](https://https://hub.docker.com/layers/blockstack/sbtc/signer-0.0.9-rc5p/images/sha256:17aeb2c93aa62c640005cfd2575b81f93e6caa409762327a4a9e99adccbe5527)`
            });

            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'docker_release_link.yaml',
              ref: context.ref,
              inputs: {
                release_id: context.payload.release.id,
                release_body: context.payload.release.body,
                release_tag: context.payload.release.tag_name
              }
            });
