name: Schedule the docker link workflow

on:
  release:
    types:
      - published

permissions:
  actions: write
  contents: read

jobs:
  trigger-delayed:
    name: Trigger Delayed Workflow
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Delayed Workflow
        uses: actions/github-script@v11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'delayed-update.yml',
              ref: context.ref,
              inputs: {
                release_id: context.payload.release.id,
                release_body: context.payload.release.body,
                release_tag: context.payload.release.tag_name
              }
            });
