name: Release workflow - Create release notes

on:
  push:
    tags:
      - '*'

permissions:
  actions: write
  contents: write
  issues: write

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

      - name: Extract Tag Name
        id: tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Generate Release Notes
        id: generate-release-notes
        run: |
          cat <<EOF > release_notes.md
          <A manual one-liner with changes>.

          [Highlights](#highlights) • [Images](#images) • [Upgrade Instructions](#upgrade-instructions)

          ## ✨ Highlights <a id="highlights">

          <A manual one-liner with changes>.

          ## 🔗 Links

          ### 🐳 Images <a id="images">

          - [\`blockstack/sbtc:signer-${{ env.TAG_NAME }}@sha256:<SignerDigest>\`](https://hub.docker.com/layers/blockstack/sbtc/signer-${{ env.TAG_NAME }}/images/sha256-<SignerDigest>)
          - [\`blockstack/sbtc:blocklist-client-${{ env.TAG_NAME }}}@sha256:<BlocklistDigest>\`](https://hub.docker.com/layers/blockstack/sbtc/blocklist-client-${{ env.TAG_NAME }}/images/sha256-<BlocklistDigest>)

          ⚠️ Always use [immutable image tags](https://docs.docker.com/reference/cli/docker/image/pull/#pull-an-image-by-digest-immutable-identifier).

          🔎 Verify the attestation of these images using [this guide](https://docs.github.com/en/actions/security-for-github-actions/using-artifact-attestations/using-artifact-attestations-to-establish-provenance-for-builds#verifying-artifact-attestations-with-the-github-cli).

          ### 📙 Database migrations

          Here: [\`signer/migrations\`](https://github.com/stacks-network/sbtc/tree/${{ env.TAG_NAME }}/signer/migrations).

          ## 🛠️ Upgrade Instructions: <a id="upgrade-instructions">

          1. Stop your sBTC signer
          2. Backup your database
          3. Edit your configuration as instructed
          4. Apply database migrations (only if not running with the \`--migrate-db\` flag)
          5. Update your sBTC images as specified above
          6. Restart your sBTC signer and blocklist client
          EOF

      - name: Create GitHub Release
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea #v7.0.01
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            const fs = require('fs');
            const releaseNotes = fs.readFileSync('release_notes.md', 'utf8');
  
            const release = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: '${{ env.TAG_NAME }}',
              name: '${{ env.TAG_NAME }}',
              body: releaseNotes,
              draft: true,
              generate_release_notes: true
            });
  
            console.log(`Created release: ${release.data.html_url}`);